services:
  plant_db:
    image: postgres:16
    container_name: plant_db
    environment:
      POSTGRES_USER: plantuser
      POSTGRES_PASSWORD: plantpass
      POSTGRES_DB: plantdb
    ports:
      - "5433:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  dbdata: